### ISSUE TITLE
re-enable notification checkbox

### ISSUE THREAD

**Issue by esanchma** [Rayquaza01/HistoryCleaner#33]
In [d5822e](https://github.com/Rayquaza01/HistoryCleaner/commit/d5822e2b57f83e9015220543e553549eb38204f2) the notification checkbox was disabled, so no matter what the user selects, a notification is always shown. Why was that changed? What is needed to re-enable the notification checkbox?

**Comment by Rayquaza01** [comment]
Previously, an optional permission was used for notifications. When this permission was granted, the checkbox would be enabled.

In the new version, the notification permission is changed from being an optional permission to a required permission. Because of this, there is no longer a situation where the checkbox is disabled.

The reason I changed the notification permission to required is mainly because having an optional permission AND a toggle for notifications is redundant. Enabling notifications involved setting two options that both essentially mean the same thing. I think it should only be one or the other.

Notifications are still only sent when the checkbox is enabled. If you do not enable notifications, History Cleaner will not send notifications.

**Comment by Rayquaza01** [comment]
I beleive this was fixed in 1.5.1. I had accidentally forgotten to check the notification setting when clearing ALL history. See https://github.com/Rayquaza01/HistoryCleaner/commit/7cf43a507051d25319ffcf8e5dcd5fabf89263df
