### ISSUE TITLE
FF 83.0 not working

### ISSUE THREAD

**Issue by ftodd1** [Rayquaza01/HistoryCleaner#9]
Does not work with FF 83.0 (64-bit).
It seems to install, i can set days, but no icon appears.  Does not seem to delete anything either.

**Comment by Rayquaza01** [comment]
Hello,
If you mean an icon doesn't appear on the toolbar, that's because this extension doesn't create a toolbar button. Once the days option is set, it runs in the background and deletes history once the browser idles (after 60 seconds). No UI outside of the options page.

If it's not deleting history, you might be having the same problem as #5. Open `Hamburger Menu > Web Developer > Browser Console`. Press the trash can icon at the top left of the window to clear the logs. Then, let your browser idle for 60 seconds. If anything new gets added to the console after history should have been deleted, post it here.

Alternatively if that doesn't yield anything useful, please try this pre-release version: https://github.com/Rayquaza01/HistoryCleaner/releases/tag/v1.2.4rc1. Install the pre-release version using `about:debugging` and then repeat the same steps as above with the Browser Console.
